export const cardArray = [
    {
      id: 0,
      title: "Первый товар",
      img: "/image/card-img.png",
      price: "170 ₽",
      date: "10 июля 11:39",
      desc: "Казань, р-н Вахитовский",
    },
    {
      id: 1,
      title: "Второй товар",
      img: "/image/card-img.png",
      price: "171 ₽",
      date: "10 июля 11:39",
      desc: "Казань, р-н Вахитовский",
    },
    {
      id: 2,
      title: "Третий товар",
      img: "/image/card-img.png",
      price: "172 ₽",
      date: "10 июля 11:39",
      desc: "Казань, р-н Вахитовский",
    },
    {
      id: 3,
      title: "Четвертый товар",
      img: "/image/card-img.png",
      price: "173 ₽",
      date: "10 июля 11:39",
      desc: "Казань, р-н Вахитовский",
    },
    {
      id: 4,
      title: "Пятый товар",
      img: "/image/card-img.png",
      price: "174 ₽",
      date: "10 июля 11:39",
      desc: "Казань, р-н Вахитовский",
    },
    {
      id: 5,
      title: "Шестой товар",
      img: "/image/card-img.png",
      price: "175 ₽",
      date: "10 июля 11:39",
      desc: "Казань, р-н Вахитовский",
    },
  ];